# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36e6256d8702088f769e1b5cbee90ca48060602ec10b4aebc425a0e3dfaf70ebcfdc194e42e0b8267ce0ffcff628eefdc6403ce53d3c0c2c9edbbe89a1ed36c

test:
  secret_key_base: 97b416b949eb98febbc8f8d10bdd073da508721e2b18bdaec77683f880edad3396a565e7a6570a60717d155047ea695d611a618e7e524fd6ab53d4e91bca11b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
